# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:

    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './EndToEndTests/EndToEndTests/'
  displayName: 'npm install'
- task: CmdLine@2
  inputs:
    script: 'npm install -g protractor'
  displayName: 'Install protractor'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'webdriver-manager clean'
  displayName: 'webdriver clean'

- task: CmdLine@2
  inputs:
    script: 'webdriver-manager update --versions.chrome=77.0.3865.40'
  displayName: 'webdriver update'

- task: CmdLine@2
  inputs:
    script: 'protractor protractor.conf.js'
    workingDirectory: './EndToEndTests/EndToEndTests/e2e/'
  displayName: 'protractor conf'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $date=$(Get-Date).ToUniversalTime().ToString('d-M-yyyy-HH');
      Write-Host "##vso[task.setvariable variable=time;]$date"
  displayName: 'Set time variable'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: 'xmlresults.xml'
#     searchFolder: '$(System.DefaultWorkingDirectory)/EndToEndTests/EndToEndTests/testResults/$(time)/'
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'xmlresults.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/EndToEndTests/EndToEndTests/testResults/$(time)/'
    testRunTitle: 'Test run 2'